// Generates assets/manifest.json (path, pack, license, source, sha256, bytes for every file)
// and assets/LICENSES.md (pack table + original license texts) from sources.json + generated.json.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import picomatch from 'picomatch';
import {
  ASSETS_DIR,
  GENERATED_PATH,
  LICENSES_NAME,
  MANIFEST_NAME,
  SOURCES_PATH,
  generatedRulesSchema,
  listFiles,
  packDir,
  packSourceUrl,
  readJson,
  sha256File,
  sourcesSchema,
  type Manifest,
  type Sources,
} from './asset-lib';

const GENERATED_DIR = 'generated';

export async function buildManifest(): Promise<Manifest> {
  const sources = await readJson(SOURCES_PATH, sourcesSchema);
  const rules = await readJson(GENERATED_PATH, generatedRulesSchema);
  const packIds = new Set(sources.packs.map((p) => p.id));
  const manifest: Manifest = { version: 1, packs: [], files: [], generated: [] };

  for (const pack of sources.packs) {
    const sourceUrl = packSourceUrl(pack);
    manifest.packs.push({
      id: pack.id,
      name: pack.name,
      author: pack.author,
      version: pack.version,
      license: pack.license,
      homepage: pack.homepage,
      sourceUrl,
    });
    const dir = packDir(pack);
    for (const rel of await listFiles(path.join(ASSETS_DIR, dir))) {
      const { sha256, bytes } = await sha256File(path.join(ASSETS_DIR, dir, rel));
      manifest.files.push({ path: `${dir}/${rel}`, pack: pack.id, license: pack.license, sourceUrl, sha256, bytes });
    }
  }

  const matchers = rules.map((rule) => {
    const unknown = rule.derivedFrom.filter((id) => !packIds.has(id));
    if (unknown.length > 0) throw new Error(`generated rule ${rule.glob} derives from unknown pack(s): ${unknown.join(', ')}`);
    return { rule, isMatch: picomatch(rule.glob) };
  });
  for (const rel of await listFiles(path.join(ASSETS_DIR, GENERATED_DIR))) {
    const full = `${GENERATED_DIR}/${rel}`;
    const hit = matchers.find((m) => m.isMatch(full));
    if (!hit) continue; // left out on purpose: assets:check reports it as undeclared
    const { sha256, bytes } = await sha256File(path.join(ASSETS_DIR, full));
    manifest.generated.push({
      path: full,
      license: hit.rule.license,
      generator: hit.rule.generator,
      derivedFrom: hit.rule.derivedFrom,
      sha256,
      bytes,
    });
  }
  return manifest;
}

async function renderLicenses(sources: Sources): Promise<string> {
  const lines = [
    '# Asset licenses',
    '',
    'Generated by `pnpm assets:manifest` from `tools/assets/sources.json`. Do not edit by hand.',
    '',
    `Allowed licenses: ${sources.licenseAllowlist.join(', ')}. Files built from these packs are listed in \`manifest.json\` under \`generated\`.`,
    '',
    '| Pack | Author | Version | License | Source |',
    '| --- | --- | --- | --- | --- |',
    ...sources.packs.map((p) => `| ${p.name} (\`${p.id}\`) | ${p.author} | ${p.version} | ${p.license} | ${p.homepage} |`),
    '',
    'Credits: art by Kenney (www.kenney.nl), emoji by Microsoft Fluent Emoji, fonts Baloo 2 and Nunito (SIL Open Font License).',
    '',
  ];
  for (const pack of sources.packs) {
    const text = await readFile(path.join(ASSETS_DIR, packDir(pack), pack.licenseFile), 'utf8');
    lines.push(`## ${pack.name} — ${pack.license}`, '', '```text', text.replace(/\r\n/g, '\n').trim(), '```', '');
  }
  return lines.join('\n');
}

export function serializeManifest(manifest: Manifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/** Regenerates manifest.json + LICENSES.md; tools that write into assets/ call this when done. */
export async function writeManifest(): Promise<Manifest> {
  const sources = await readJson(SOURCES_PATH, sourcesSchema);
  const manifest = await buildManifest();
  await writeFile(path.join(ASSETS_DIR, MANIFEST_NAME), serializeManifest(manifest));
  await writeFile(path.join(ASSETS_DIR, LICENSES_NAME), await renderLicenses(sources));
  return manifest;
}

async function main(): Promise<void> {
  const manifest = await writeManifest();
  console.log(`assets:manifest wrote ${manifest.files.length} pack files + ${manifest.generated.length} generated files`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
