// English twins of the villagers' and animals' speech-bubble lines (ambient-lines.ts, everyday-routines.ts): the
// same pools, the same number of lines in the same order (ambient-lines.test.ts keeps them in step). `{name}` is the
// child's character name.
export const AMBIENT_LINES_EN: Readonly<Record<string, readonly string[]>> = {
  'woodcutter-greet': ['Hello {name}! Where are you off to?', 'Oh look, it\'s {name}!', 'Mind the wood chips, {name}!'],
  'woodcutter-work': ['Heave-ho! One more log!', 'Phew, it\'s hot today!', 'This wood will keep us warm in winter.', 'Only the dead trees get chopped!'],
  'woodcutter-rest': ['Time for a sip of water.', 'Lovely cool afternoon, isn\'t it?', 'My back aches, a short break!'],
  'woodcutter-chat': ['I only cut dry trees, {name}.', 'Young trees grow into a forest.', 'Doesn\'t the axe sound cheerful?', 'Campfire tonight, I\'ll light it!'],
  'fisher-greet': ['Shh, tiptoe please, {name}!', 'Hi {name}! The fish are biting.', 'Sit and watch me fish!'],
  'fisher-catch': ['Aha, I caught a fish!', 'What a big one! Back you go.', 'Swim away, fishy, grow up fast!'],
  'fisher-miss': ['Oh no, it got away!', 'Missed! Let\'s try again.', 'Clever little fish!'],
  'fisher-chat': ['I let the fish go after.', 'Be patient and the fish will come.', 'The stream is so cool, {name}.'],
  'gardener-greet': ['Hi {name}! Want to see my veggies?', '{name}\'s come to visit!', 'Are my greens green enough, {name}?'],
  'gardener-harvest': ['Look how big this carrot is!', 'The veggies are so fresh today!', 'Veggie soup tomorrow!'],
  'gardener-chat': ['I water every morning.', 'Worms keep the soil soft.', 'Tiny seeds grow into plants!', 'Bees mean fruit is on its way.'],
  'cook-greet': ['{name}, are you hungry yet?', 'Hi {name}! The soup\'s nearly done.', 'Come and warm up, {name}!'],
  'cook-taste': ['Mmm, just right!', 'A pinch more salt.', 'Smells wonderful!'],
  'cook-call': ['Food\'s ready, come and eat!', 'Who wants hot soup?', 'Everyone, take a break!'],
  'cook-thanks': ['Thank you, dear!', 'Well done, that\'s plenty of wood!', 'Put the wood by the fire for me.'],
  'cook-chat': ['I\'m making pumpkin soup.', 'Too big a fire burns the pot.', 'Eat well, play hard!', 'Wash your hands before eating!'],
  'carrier-greet': ['Hi {name}! Want to play?', 'Hey {name}! I\'m carrying firewood.', 'Hiya {name}!'],
  'carrier-deliver': ['Granny, here\'s the wood!', 'I brought the firewood home!', 'One more bundle coming!'],
  'carrier-play': ['Tag is so much fun!', 'You can\'t catch me!', 'Hee hee, hurry up!'],
  'carrier-parrot': ['Vẹt, come down and play!', 'Vẹt flies so high!', 'Hello, Vẹt!'],
  'carrier-chat': ['I help Granny light the fire.', 'Let\'s pick mushrooms tomorrow!', 'I counted five bundles of wood!', '{name}, you run so fast!'],
  'woodcutter-cheer': ['Hooray for {name}! Well done!', 'I\'m raising my axe for you!', 'Our forest has a hero now!'],
  'fisher-cheer': ['Fantastic, {name}!', 'Even the fish are jumping for joy!', 'I\'m clapping the loudest!'],
  'gardener-cheer': ['Great job, {name}! Have a flower!', 'Even my veggies are nodding!', 'Oh, {name}, you did it!'],
  'cook-cheer': ['Sweet soup tonight to celebrate!', 'What a clever grandchild!', '{name}, come here for a kiss!'],
  'carrier-cheer': ['Yeah! {name} is awesome!', 'High five, {name}!', 'I\'m jumping for joy!'],
  'parrot-cheer': ['{name} wins! Champion, champion!', 'Hooray! Hooray!', 'Vẹt sings for {name}!'],
  'village-reply': ['Yes, that\'s right!', 'Nicely done!', 'Take a little rest.', 'How lovely!', 'Ha ha, spot on!'],
  'parrot-greet': ['Hello {name}! Hello!', '{name}! {name}!', 'Vẹt says hi to {name}!'],
  'parrot-sing': ['La la la!', 'Cuckoo, cuckoo!', 'Pretty forest, pretty forest!'],
  'parrot-trick': ['Watch Vẹt jump!', 'Vẹt is dancing!', 'Bravo, {name}!'],
  'bee-buzz': ['Bzz, bzz!', 'Off to find nectar!', 'Buzzz!'],
  'bunny-sound': ['The bunny pricks up its ears at {name}.', 'The bunny stands up to look at {name}.', 'The bunny\'s nose twitches.'],
  'bunny-trick': ['The bunny hops in a circle!', 'The happy bunny bounces!', 'Tee hee!'],
  'deer-sound': ['The deer looks up at {name}.', 'The deer flicks its ears.', 'The deer watches {name} curiously.'],
  'deer-trick': ['The deer bows to {name}.', 'The deer nuzzles {name}\'s hand.', 'The deer wiggles its ears happily.'],
  'fox-greet': ['Hi {name}, I just woke up.', 'Who\'s there? Oh, {name}!', 'Hmm, hello {name}!'],
  'fox-snore': ['Snore, snore...', 'Zzz...', 'Mmm... five more minutes...'],
  'fox-trick': ['The fox does a somersault!', 'The fox waves its tail!', 'Hee, that tickles!'],
  'hog-sound': ['Oink oink!', 'Oink, yummy mushrooms!', 'Sniff sniff!'],
  'hog-trick': ['The hog wiggles its bottom, oink!', 'The hog rolls right over!', 'Oink oink, what fun!'],
  'chick-sound': ['Cheep cheep!', 'Peep peep!', 'Cheep! Cheep cheep!'],
  'crab-greet': ['The crab waves a claw at {name}!', 'Look, I walk sideways!', 'Click clack!'],
  'crab-trick': ['The crab waves its claws!', 'The crab does the crab dance!', 'Click clack clack!'],
  'fish-splash': ['Plop!', 'Splash!', 'Sploosh!'],
  'caterpillar-greet': ['A little caterpillar greets {name}.', 'The caterpillar is munching a leaf.', 'The caterpillar inches along.'],
  'caterpillar-trick': ['The caterpillar curls up and smiles!', 'The caterpillar waves and waves!', 'That tickles!'],
  'vendor-greet': ['Hello {name}! What would you like?', 'Come have a look, {name}!', 'All fresh today, dear!'],
  'vendor-work': ['Fresh-picked greens here!', 'Sweet fruit, come and buy!', 'Fresh flowers, fresh flowers!'],
  'vendor-chat': ['I set up my stall at dawn.', 'Market day is so lively.', 'Buy more and I\'ll knock a bit off.'],
  'vendor-cheer': ['Well done {name}, have a fruit!', 'Hooray for the clever kid!', 'Come on, whole market, clap!'],
  'vendor-reply': ['Thank you kindly!', 'Could I buy some, please?', 'Your goods look lovely!'],
  'shopper-greet': ['Hi {name}, shopping today?', 'Oh, {name}\'s at the market too!', 'Fun market today, isn\'t it?'],
  'shopper-work': ['How much for these greens?', 'A kilo of oranges, please!', 'Is this one ripe yet?'],
  'shopper-chat': ['Greens for my soup.', 'We have guests this afternoon.', 'I always pick the biggest one.'],
  'shopper-cheer': ['Oh, {name}, how clever!', 'I\'m so happy for you!', 'Wonderful, wonderful!'],
  'shopper-reply': ['A little discount, please?', 'Two bunches for me!', 'So tasty, I\'ll buy more!'],
  'porter-greet': ['Coming through, {name}!', 'Hi there! This load is heavy.', 'Hey, it\'s {name}!'],
  'porter-work': ['Two, three, lift!', 'This rice sack is so heavy!', 'Over to that stall it goes!'],
  'porter-chat': ['I\'ve carried loads all morning.', 'A full load every trip.', 'A good meal keeps me strong.'],
  'porter-cheer': ['I lift my pole for you!', 'Brilliant, {name}!', 'You\'re the best!'],
  'ferryman-greet': ['Crossing the river, {name}?', 'The boat\'s heading across!', 'Hello! Sit tight now!'],
  'ferryman-work': ['Row, row, row!', 'The water\'s so calm today.', 'Tie the boat up tight.'],
  'ferryman-chat': ['Thirty years I\'ve rowed this boat.', 'Our river is a gentle one.', 'In flood season the water rises.'],
  'ferryman-cheer': ['I tap my oar for you!', 'Well done, little one!', 'The whole riverbank cheers!'],
  'planter-greet': ['Hi! Off to the fields?', 'Watch me plant rice, {name}!', 'The paddy looks lovely today!'],
  'planter-work': ['Plant them in straight rows!', 'Bright green seedlings here.', 'Wading keeps my feet cool.'],
  'planter-chat': ['Three months till the rice ripens.', 'Rice feeds the whole village.', 'After planting, I\'ll cook rice.'],
  'planter-cheer': ['I wave my seedlings for you!', 'You grow clever like rice!', 'Oh, amazing, {name}!'],
  'kite-greet': ['{name}, want to fly a kite?', 'The wind\'s up, let\'s play!', 'My kite flies the highest!'],
  'kite-work': ['Higher, higher!', 'It\'s wobbling, hold tight!', 'Whoosh, whoosh!'],
  'kite-chat': ['I made this kite myself.', 'I come to the dyke every afternoon.', 'Kite whistles sing so sweetly.'],
  'kite-cheer': ['Yeah! {name} is super!', 'My kite dances for you!', 'Gimme five, {name}!'],
  'home-cook-greet': ['Come on in, {name}!', 'Dinner\'s almost ready, dear.', 'Hello, my good child!'],
  'home-cook-work': ['A bit of spring onion for flavour.', 'The rice is bubbling now.', 'This sour soup is yummy!'],
  'home-cook-chat': ['I cook for the whole family.', 'Home cooking is the best.', 'Wash your hands, then come eat.'],
  'home-cook-cheer': ['Here\'s a treat for you!', 'My grandchild is so clever!', 'Give Granny a cuddle!'],
  'laundry-greet': ['Hi there! Lovely sunshine.', 'Help me hang the washing, {name}?', 'Oh, you\'ve come to visit!'],
  'laundry-work': ['Shake out the shirt nice and flat.', 'It\'ll dry fast in this sun.', 'Peg it so the wind can\'t take it.'],
  'laundry-chat': ['White shirts need the sun.', 'I fold the clothes in the afternoon.', 'Sun-dried clothes smell lovely.'],
  'laundry-cheer': ['I wave my towel for you!', 'Way to go, {name}!', 'Happy as a festival day!'],
  'waterer-greet': ['Hello! Want to see the garden?', 'Grandpa says hi, {name}.', 'My garden\'s in bloom!'],
  'waterer-work': ['Water the roots, drink up!', 'Grow fast, little plants.', 'So dry, a bit more water.'],
  'waterer-chat': ['I\'ve planted trees since I was small.', 'Plants need sun and water.', 'I\'ll pick greens for you tomorrow.'],
  'waterer-cheer': ['Grandpa\'s so proud of you!', 'The flowers are smiling at you!', 'Marvellous, {name}!'],
  'milker-greet': ['Hello! The cow is very gentle.', 'Fancy some milk, {name}?', 'Come watch me milk the cow!'],
  'milker-work': ['A full bucket of milk!', 'Good cow, stand still now.', 'Fresh, cool milk!'],
  'milker-chat': ['I milk the cow every morning.', 'Young grass keeps cows healthy.', 'This milk makes tasty cakes.'],
  'milker-cheer': ['The whole barn cheers for you!', 'Bravo, bravo!', 'Here\'s a glass of milk for you!'],
  'hen-keeper-greet': ['Hi! The hens are eating.', 'Collect eggs with me, {name}!', 'Lots of eggs in the nest today!'],
  'hen-keeper-work': ['Here chook chook, dinner time!', 'A handful of grain for the hens.', 'These eggs are still warm.'],
  'hen-keeper-chat': ['The hens lay every day.', 'Chicks follow mum for food.', 'Please don\'t chase the hens.'],
  'hen-keeper-cheer': ['Even the hens cluck for you!', 'I\'m clapping hardest of all!', 'Lovely work, {name}!'],
  'ploughman-greet': ['Hello! Nice field, isn\'t it?', 'Watch me plough, {name}!', 'Soft soil is ready for seeds.'],
  'ploughman-work': ['One more row to dig!', 'Soft earth, easy ploughing.', 'Heave-ho, keep going!'],
  'ploughman-chat': ['Corn this season.', 'Rainy season, plants grow fast.', 'Earthworms loosen the soil.'],
  'ploughman-cheer': ['I raise my hoe for you!', 'You\'re really good at this!', 'Three cheers for {name}!'],
  'sweeper-greet': ['Hi! Is the yard clean yet?', 'Have fun at school, {name}!', 'Sweeping up the fallen leaves.'],
  'sweeper-work': ['So many yellow leaves!', 'Into one pile now.', 'Clean and tidy!'],
  'sweeper-chat': ['Bin your rubbish, please.', 'A clean yard makes school fun.', 'I sweep from early morning.'],
  'sweeper-cheer': ['You\'re so clever!', 'Great, just great!', 'The whole yard is happy for you!'],
  'guard-greet': ['Morning! Off to class now.', 'Hello there, {name}!', 'Stay on the crossing lines.'],
  'guard-work': ['All is well.', 'The gate\'s open, in you go.', 'I keep a careful eye on the gate.'],
  'guard-chat': ['Ten years guarding this gate.', 'Look both ways crossing the road.', 'Our school is the loveliest.'],
  'guard-cheer': ['A flag-day salute for you!', 'Well done, good student!', 'I\'m so proud of you!'],
  'pupil-greet': ['Hey {name}, play with me!', 'Hi, new friend!', 'Break time is so fun!'],
  'pupil-work': ['Kick! Catch!', 'Skipping time, one, two!', 'I won!'],
  'pupil-chat': ['I\'m in Year Two.', 'Maths test tomorrow.', 'My teacher is so kind.'],
  'pupil-cheer': ['You\'re the best in class!', 'Slap me five, {name}!', 'Hooray for my friend!'],
  'pupil-reply': ['Pass it to me!', 'Can I play again?', 'That\'s so cool!'],
  'teacher-greet': ['Good morning, {name}!', 'You\'re early today!', 'Hello there, dear.'],
  'teacher-work': ['Eyes on me, everyone.', 'Today\'s lesson is a fun one.', 'Write neatly, now.'],
  'teacher-chat': ['Read a book every day.', 'I love our class.', 'Having fun helps you learn.'],
  'teacher-cheer': ['A gold star for you!', 'Excellent work, {name}!', 'Everyone, give a clap!'],
  'reader-greet': ['Shh, hi {name}.', 'This book is really good.', 'Want to read together?'],
  'reader-work': ['This page has a lovely picture.', 'What a great story.', 'Just one more chapter.'],
  'reader-chat': ['I love fairy tales.', 'The library is so quiet.', 'You can borrow books to take home.'],
  'reader-cheer': ['You\'re like a storybook hero!', 'You\'re brilliant, {name}!', 'Super duper!'],
  'librarian-greet': ['Hello! Looking for a book?', 'The library is open.', 'Come in, {name}.'],
  'librarian-work': ['Books go in ABC order.', 'This one goes on shelf three.', 'Time to dust the books.'],
  'librarian-chat': ['Return books on time, please.', 'Books are the best friends.', 'Read quietly, dear.'],
  'librarian-cheer': ['Here\'s a bookmark for you!', 'A real bookworm!', 'Hooray, good reader!'],
  'sentry-greet': ['Greetings, Sir {name}!', 'Who approaches the castle?', 'Enter, the gate is open!'],
  'sentry-work': ['Keep a sharp watch!', 'All quiet up on the tower.', 'Change of guard!'],
  'sentry-chat': ['The castle has a hundred steps.', 'I guard the castle gate.', 'You can see far from the tower.'],
  'sentry-cheer': ['Welcome, champion!', 'The castle celebrates you!', 'Brave knight {name}, well done!'],
  'trumpeter-greet': ['Toot toot! Hi {name}!', 'Listen to my trumpet!', 'Hello, music lover!'],
  'trumpeter-work': ['Ta-ta-ta-daa!', 'One more tune!', 'The trumpet rings through town!'],
  'trumpeter-chat': ['I play every morning.', 'Music makes everyone happy.', 'This was my grandpa\'s trumpet.'],
  'trumpeter-cheer': ['Toot toot for the winner!', 'A victory tune for you!', 'Sound the horns, hooray!'],
  'cow-sound': ['The cow goes: moo!', 'The cow swishes its tail at {name}.', 'The cow munches happily.'],
  'pig-sound': ['Oink, oink, oink!', 'The pig snuffles in the dirt.', 'The piglet rolls around.'],
  'dog-sound': ['Woof woof! Hi {name}!', 'The pup wags its tail like mad.', 'The pup bounces round your feet.'],
  'cat-sound': ['Meow meow!', 'The cat rubs its head on {name}.', 'The cat stretches out lazily.'],
  'penguin-sound': ['Squawk squawk!', 'A penguin waddles up to {name}.', 'The penguin flaps its little wings.'],
  'penguin-trick': ['The penguin belly-slides on ice!', 'The penguin spins around!', 'Squawk! Watch me jump!'],
  'polar-bear-sound': ['Grr... hello {name}.', 'The polar bear waves a big paw.', 'The polar bear sniffs for fish.'],
  'polar-bear-trick': ['The polar bear rolls in the snow!', 'The polar bear stands up to wave!', 'The polar bear shakes off snow!'],
  'polar-bear-snore': ['Snooore... snooore...', 'The bear naps on soft snow.', 'Zzz... yummy fish...'],
  'monkey-sound': ['Ooh ooh aah aah!', 'The monkey scratches its head at {name}.', 'The monkey offers {name} a banana.'],
  'monkey-trick': ['The monkey does a flip!', 'The monkey swings and waves at {name}!', 'Ooh ooh! Watch me dance!'],
};
