// What villagers and animals say in their speech bubbles. Short lines (a child reads them while
// walking), each pool rotating without repeating a line back to back. `{name}` is the child's
// character name. Nothing here teaches or grades: learning lives in quests.
import { EVERYDAY_LINES } from './everyday-routines';

export const AMBIENT_LINES: Readonly<Record<string, readonly string[]>> = {
  'woodcutter-greet': ['Chào {name}! Đi đâu đấy cháu?', 'Ơ kìa, {name} đấy à!', 'Cẩn thận dăm gỗ nhé {name}!'],
  'woodcutter-work': ['Hây dô! Thêm khúc nữa!', 'Phù, nóng quá đi mất!', 'Gỗ này để sưởi mùa đông.', 'Chặt cây khô thôi nhé!'],
  'woodcutter-rest': ['Nghỉ tay uống ngụm nước đã.', 'Chiều nay trời mát ghê.', 'Mỏi lưng quá, nghỉ chút!'],
  'woodcutter-chat': ['Bác chỉ chặt cây khô thôi, {name} ạ.', 'Cây non để lớn thành rừng.', 'Tiếng rìu nghe vui tai không?', 'Tối nay bác nhóm lửa trại!'],
  'fisher-greet': ['Suỵt, {name} đi nhẹ thôi!', 'Chào {name}! Cá đang cắn câu.', 'Ngồi xem chú câu nhé!'],
  'fisher-catch': ['A, được một chú cá!', 'Cá to quá! Thả về nhé.', 'Bơi đi cá ơi, lớn nhanh nhé!'],
  'fisher-miss': ['Ôi, cá chạy mất rồi!', 'Hụt rồi, thử lại nào.', 'Cá khôn ghê!'],
  'fisher-chat': ['Câu xong chú thả cá về suối.', 'Kiên nhẫn là câu được cá.', 'Nước suối mát lắm {name} ạ.'],
  'gardener-greet': ['Chào {name}! Xem luống rau không?', '{name} đến chơi đấy à!', 'Rau cô xanh chưa {name}?'],
  'gardener-harvest': ['Củ cà rốt to chưa này!', 'Rau hôm nay tươi ghê!', 'Mai nấu canh rau nhé!'],
  'gardener-chat': ['Tưới nước mỗi sáng đấy.', 'Giun giúp đất tơi xốp.', 'Hạt nhỏ thôi mà mọc thành cây!', 'Ong đến là hoa sắp ra quả.'],
  'cook-greet': ['{name} ơi, đói bụng chưa?', 'Chào {name}! Nồi canh sắp chín.', 'Vào đây sưởi ấm nào {name}!'],
  'cook-taste': ['Ừm, vừa ăn rồi!', 'Thêm chút muối nữa.', 'Thơm quá đi!'],
  'cook-call': ['Cơm chín rồi, về ăn thôi!', 'Ai ăn canh nóng nào?', 'Mọi người ơi, nghỉ tay!'],
  'cook-thanks': ['Cảm ơn cháu nhé!', 'Giỏi quá, đủ củi rồi!', 'Để củi gần lửa giúp bà.'],
  'cook-chat': ['Bà nấu canh bí đấy.', 'Lửa to quá là cháy nồi.', 'Ăn no mới chơi khỏe!', 'Nhớ rửa tay trước khi ăn nhé!'],
  'carrier-greet': ['Chào {name}! Chơi với tớ không?', 'Ê {name}! Tớ đang gánh củi.', 'Hi {name}!'],
  'carrier-deliver': ['Bà ơi, củi đây ạ!', 'Cháu mang củi về rồi!', 'Thêm một bó nữa nè!'],
  'carrier-play': ['Đuổi bắt vui quá!', 'Không bắt được tớ đâu!', 'Hí hí, nhanh lên nào!'],
  'carrier-parrot': ['Vẹt ơi, xuống đây chơi!', 'Vẹt bay cao quá!', 'Chào Vẹt nhé!'],
  'carrier-chat': ['Tớ giúp bà nhóm lửa đấy.', 'Mai mình đi hái nấm nhé!', 'Tớ đếm được năm bó củi!', '{name} chạy nhanh ghê!'],
  'woodcutter-cheer': ['Hoan hô {name}! Giỏi quá!', 'Bác giơ rìu chúc mừng nè!', 'Rừng mình có anh hùng rồi!'],
  'fisher-cheer': ['Tuyệt cú mèo, {name} ơi!', 'Cá cũng nhảy mừng cháu kìa!', 'Chú vỗ tay to nhất!'],
  'gardener-cheer': ['Giỏi ghê, {name}! Tặng cháu bông hoa!', 'Rau cô cũng gật gù khen!', 'Ôi, {name} làm được rồi!'],
  'cook-cheer': ['Tối nay bà nấu chè mừng!', 'Cháu bà giỏi quá đi!', '{name} ơi, bà thơm má nào!'],
  'carrier-cheer': ['Yeah! {name} siêu ghê!', 'Đập tay cái nào {name}!', 'Tớ nhảy cẫng lên luôn!'],
  'parrot-cheer': ['{name} vô địch! Vô địch!', 'Hoan hô! Hoan hô!', 'Vẹt hát mừng {name} nè!'],
  'village-reply': ['Ừ, đúng đấy!', 'Làm tốt lắm!', 'Nghỉ chút đi nào.', 'Hay quá nhỉ!', 'Ha ha, chuẩn luôn!'],
  'parrot-greet': ['Xin chào {name}! Xin chào!', '{name}! {name}!', 'Vẹt chào {name} nè!'],
  'parrot-sing': ['La la la!', 'Tu hú, tu hú!', 'Rừng đẹp quá, đẹp quá!'],
  'parrot-trick': ['Xem Vẹt nhảy nè!', 'Vẹt múa đây!', 'Hoan hô {name}!'],
  'bee-buzz': ['Vo ve, vo ve!', 'Ong đi hút mật!', 'Vù vù!'],
  'bunny-sound': ['Thỏ vểnh tai nghe {name}.', 'Thỏ đứng lên nhìn {name}.', 'Mũi thỏ khụt khịt.'],
  'bunny-trick': ['Thỏ nhảy vòng tròn!', 'Thỏ vui quá, nhảy tưng tưng!', 'Hí hí!'],
  'deer-sound': ['Nai ngẩng đầu nhìn {name}.', 'Nai khẽ vẫy tai.', 'Nai nhìn {name} tò mò.'],
  'deer-trick': ['Nai cúi đầu chào {name}.', 'Nai dụi mũi vào tay {name}.', 'Nai lắc tai vui vẻ.'],
  'fox-greet': ['Chào {name}, tớ vừa ngủ dậy.', 'Ai đấy? À, {name}!', 'Hừm, chào {name}!'],
  'fox-snore': ['Khò khò...', 'Zzz...', 'Ư... năm phút nữa thôi...'],
  'fox-trick': ['Cáo lộn một vòng!', 'Cáo vẫy đuôi chào!', 'Hí, nhột quá!'],
  'hog-sound': ['Ụt ịt!', 'Ụt ụt, nấm ngon ghê!', 'Khịt khịt!'],
  'hog-trick': ['Heo lắc mông, ụt ịt!', 'Heo lăn một vòng!', 'Ụt ịt, vui quá!'],
  'chick-sound': ['Chíp chíp!', 'Chiếp chiếp!', 'Chíp! Chíp chíp!'],
  'crab-greet': ['Cua giơ càng chào {name}!', 'Cua bò ngang nè!', 'Tách tách!'],
  'crab-trick': ['Cua múa càng!', 'Cua nhảy điệu cua!', 'Tách tách tách!'],
  'fish-splash': ['Tõm!', 'Bõm!', 'Ào!'],
  'caterpillar-greet': ['Sâu nhỏ chào {name}.', 'Sâu đang ăn lá.', 'Sâu bò chầm chậm.'],
  'caterpillar-trick': ['Sâu uốn mình cười!', 'Sâu vẫy vẫy!', 'Nhột quá!'],
  ...EVERYDAY_LINES,
};
